### ISSUE TITLE
No AVP2SP.REZ found

### ISSUE THREAD

**Issue by Keith94** [SuiMachine/AVP2-Custom-Launcher#1]
The launcher throws that error when trying to run it. But my game folder doesn't seem to include the file it's looking for. Any ideas why it's missing, or can you attach the file here? Thanks.

![explorer_2016-10-19_11-46-03](https://cloud.githubusercontent.com/assets/5490615/19532767/046b5124-95f2-11e6-8372-7fe4e63fb993.png)

**Comment by SuiMachine** [comment]
AVP2SP.REZ is a part of Singleplayer Map Update #1
http://community.pcgamingwiki.com/files/file/206-aliens-versus-predator-2-single-player-map-update-1/

**Comment by Keith94** [comment]
Ahh thanks, I was using only 1.0.9.6

The first time I try to save game settings in the launcher, it gives the following error (the game is closed)

![avp_customlauncher_2016-10-20_03-11-25](https://cloud.githubusercontent.com/assets/5490615/19555865/62dccd06-9673-11e6-8ed9-39ab99b47595.png)

Also if I enable aspect ratio fix and launch into the game, it gives this error too..

![lithtech_2016-10-20_03-08-27](https://cloud.githubusercontent.com/assets/5490615/19555891/7a2557da-9673-11e6-8aa4-f3de504c94b7.png)

**Comment by SuiMachine** [comment]
For VCRUNTIME140D.dll try installing Redistributable for Visual Studio 2015 - https://www.microsoft.com/en-us/download/details.aspx?id=48145 and see if it helps. If it doesn't, I'll look into it further.

First exception thing is a bug on my part.

**Comment by Keith94** [comment]
Oh, it seems I had that redistributable already installed, I tried "Repair" options but it didn't fix the issue for me.

**Comment by SuiMachine** [comment]
Damn it, forgot to mention, did you install the x86 version. I know it may sound weird to install x86 on 64bit system, but in this case it's about having proper libraries to launch 32-bit application.

**Comment by Keith94** [comment]
Yeah I did, I reinstalled both x86 and x64 but I still get the error.

**Comment by SuiMachine** [comment]
Alright, I guess that is also my fault. Try this build:
https://github.com/SuiMachine/AVP2-Custom-Launcher/releases/tag/0.6.1

**Comment by Keith94** [comment]
Nice, the latest version solved all error popups for me. The only popup I see is the warning about "avp2cmds.txt" when first starting launcher.

Also as a test, I replaced AVP2SP.REZ with a dummy (blank) file with the same name, and the custom launcher seems to work fine. Does it still require to have the file present?

**Comment by SuiMachine** [comment]
You could be having all of the rez files as dummies, since it only checks filenames (doesn't actually check sizes and content - although then LithTech.exe would crash). The point was to somewhat make sure that people have the game patched, since otherwise the instructions and variables may be allocated in different places in memory.

**Comment by Keith94** [comment]
I see, thanks for your answer. I guess I'll close this one.
