### ISSUE TITLE
Start launcher centered on screen

### ISSUE THREAD

**Issue by Keith94** [SuiMachine/AVP2-Custom-Launcher#2]
The original launcher for the game always starts at the center of the screen; the custom launcher opens more towards the top left corner of the screen. Would it be a good idea to position it at the center as well?

**Comment by SuiMachine** [comment]
Can probably make it start in the middle and then write down the position for the next launch.

**Comment by Keith94** [comment]
Yep, sounds good to me.

**Comment by Keith94** [comment]
Btw, the Twitch link in the Readme file doesn't work, I think it's missing "https://".

**Comment by Keith94** [comment]
Hmm, in v0.6.2 if `autoexecextended.cfg` isn't found, the program still opens at top left (X:52, Y:52). Once game settings are saved, last position is remembered correctly.

Also, should the position of "game settings" window be saved too?
