### ISSUE TITLE
Multiplayer Master Server is online

### ISSUE THREAD

**Issue by ZTXH** [SuiMachine/AVP2-Custom-Launcher#3]
The Description cites not having been able to test the Custom Launcher in multiplayer on account of the servers being down. Such is no longer the case, unless the Dev team here is already aware of that.

The site and forums are located at http://tbbcbase.net/

I've been able to play on them, albeit, well, my monitor is all sorts of whacked out, which led me to this page. Will test it on MP soon after this post!

**Comment by ZTXH** [comment]
...also can now confirm that using the Alt Launcher on Multiplayer will be detected by their autoban system. Which also works.

**Comment by SuiMachine** [comment]
There is literally no dev team. It's me and me alone :stuck_out_tongue: 

Idk, maybe I'll look into it in March, but I make no promises.

**Comment by ZTXH** [comment]
Well hey, you're still around! Little glimmer of hope.

Thank you for the reply! I linked your page here to the TBBC forums. Perhaps someone might be able to contribute.

**Comment by SuiMachine** [comment]
I added a basic check for one of the files added by TBBC. Launcher should now disable its widescreen hack (trainer and injection) as well as disable certain options under game settings, which should make it completely safe to use with TBBC. Then again, they did far better job, than me, to a point where my launcher gets kind of pointless  :+1:

**Comment by ZTXH** [comment]
Well, maybe it points to them and builds the community. Or brings some closure for you on the project.

Thank you for your time!
