### ISSUE TITLE
Command line paramete

### ISSUE THREAD

**Issue by cyberconan** [SuiMachine/AVP2-Custom-Launcher#4]
Hi!
Excellent job, I'm using now your launchers for AvP2 & AvP2-hunt. It's possible include a command line parameter for AVP_CustomLauncher.exe than launch the game with previous setup instead click in "Start the game"?
Thanks a lot of!!

**Comment by SuiMachine** [comment]
Sure.

**Comment by SuiMachine** [comment]
You should now be able to skip launcher by using `-skiplauncher` (it's not character case specific) command line parameter. Other parameters send to custom launcher should also be transferred to lithtech.exe. And I removed administrator requirement. Still, if there is an issue with widescreen fixer not working, try running launcher as administrator.

**Comment by cyberconan** [comment]
Excellent! Thank you very much!!
