### ISSUE TITLE
Issue non English Version

### ISSUE THREAD

**Issue by Choum28** [SuiMachine/AVP2-Custom-Launcher#5]
Hello,

Is it possible to remove or make optionnal the check/dependency of AVP2SP.REZ file which is the file added by the singleplayer map update.
The update was only for the English version of the game (and cannot been installed on other version).

French version and I suppose all others non English versions already have this fix include in their avp2.rez file (main game file).
I have check all files inside the AVP2SP.REZ, and confirm they are already include (same version/crc) in the avp2.rez of the fra version.

Sincerely,

**Comment by Choum28** [comment]
I manage to use the launcher in 2 different way

- extract the file from avp2_en_sp1.exe with installshield cabinet and copy it into my gamefolder.

- Or more simple just create an empty file name AVPSP1.rez with notepad and put it in the gamefolder also work.

**Comment by SuiMachine** [comment]
I'll just remove the requirement. And for MP as well -I don't think they affect the renderer or exe file, so the widescreen hack should still work.

**Comment by Choum28** [comment]
Thank

I confirm

- The single player patch update only some level and textures.
- Multiplayer patche only add new mp maps.

none of them affect the exe, dll.

**Comment by SuiMachine** [comment]
https://github.com/SuiMachine/AVP2-Custom-Launcher/releases/tag/1.1.0

**Comment by Choum28** [comment]
Work perfectly :)

**Comment by SuiMachine** [comment]
K. Issue solved.
