### ISSUE TITLE
jackfustes D3DIM700.dll link is dead

### ISSUE THREAD

**Issue by iamtakingiteasy** [SuiMachine/AVP2-Custom-Launcher#8]
http://www.wsgf.org/forums/viewtopic.php?p=155982#p155982 does not lead anywhere

**Comment by iamtakingiteasy** [comment]
Apparently this is it: http://www.wsgf.org/dr/aliens-versus-predator-2-gold-edition ; in archive

**Comment by iamtakingiteasy** [comment]
Probably best to just add this DLL to release.

**Comment by SuiMachine** [comment]
Yeah, I just added it to release. God damn google and just mass marking their website as dangerous....

**Comment by iamtakingiteasy** [comment]
Thank you.
